/* eslint-disable import/prefer-default-export */
export const defaultDataBast = {
  noReference: null,
  letterDate: null,
  nameLandlord: null,
  locationAddress: null,
  locationName: null,
  atmId: null,
  latitude: null,
  longitude: null,
  areaName: null,
  cityName: null,
  picVendor: null,
  ticketNumber: null,
  locationId: null,
  // PAYLOAD BELOW
  idMesin: null,
  jobType: null,
  requestDate: null,
  processingDate: null,
  notesDescription: null,
  engineerPhone: null,
  mesinType: null,
  statusSubmit: null,
  stickerId: null,
  kelengkapanStiker: null,
  boothType: null,
  mesin: null,
  snMesin: null,
  upsBrand: null,
  snUps: null,
  jumlahKaset: null,
  jumlahReject: null,
  dynabolt: null,
  kondisiAc:null,
  kondisiBooth:null,
  teganganListrikOtlet: null,
  teganganListrikBooth: null,
  groundListrikOtlet: null,
  groundListrikBooth: null,
  cctvInternal: null,
  cctvDvr: null,
  statusMesin: null,
  testingTransaksiKartu: null,
  testingTransaksiOctom: null,
  kerapihanKabel: null,
  cahayaRuangan: null,
  kebersihanRuang: null,
  merekModem: null,
  hub: null,
  snModem: null,
  merekMesin: null,
  requesterName: null,
  
  photoFrontCimb: null,
  dateFrontCimb: null,
  photoLeftCimb: null,
  dateLeftCimb: null,
  photoRightCimb: null,
  dateRightCimb: null,
  photoRearCimb: null,
  dateRearCimb: null,

  photoFrontVendor: null,
  dateFrontVendor: null,
  photoLeftVendor: null,
  dateLeftVendor: null,
  photoRightVendor: null,
  dateRightVendor: null,
  photoRearVendor: null,
  dateRearVendor: null,

  photoFLMVendor: null,
  photoSLMVendor: null,

  photoList: [],
  vendorDetails: [
    {
      check: "checkedCR",
      phone: "",
      name: "",
      key: "CR",
    },
    {
      check: "checkedFLM",
      phone: "",
      name: "",
      key: "FLM",
    },
    {
      check: "checkedSLM",
      phone: "",
      value: "",
      key: "SLM",
    },
    {
      check: "checkedSecurity",
      phone: "",
      name: "",
      key: "Security",
    },
    {
      check: "checkedVendorJaringan",
      phone: "",
      name: "",
      key: "Jaringan",
    },
    {
      check: "checkedVendorMaintenance",
      phone: "",
      name: "",
      key: "Maintenance",
    },
    {
      check: "checkedVendorMediaPromosi",
      phone: "",
      name: "",
      key: "Promosi",
    },
    {
      check: "checkedVendorSurvey",
      phone: "",
      name: "",
      key: "Survey",
    },
    {
      check: "checkedOthers",
      phone: "",
      name: "",
      key: "Other",
    },],

  kunciBooth: 0,
  kunciFasciaAtas:0,
  kunciFasciaBawah:0,
  kunciKerangkeng:0,
  kunciTombak: 0,
  vendorSignature: [],
  photoSignature: null,
};