const dataDummy = [
  {
    id: 1,
    approvalId: 1081,
    requesterId: 112801,
    namaRequestor: "Adara Fredelia Ulani",
    requestDate: "03/02/2022",
    idMesin: "ZZ08",
    location: "Tangerang Supermall Karawaci",
    jenisAsuransi: "Cash Machine",
    typeTransaksi: "New",
    harga: "Rp15.000.000",
    sla: "tes",
    approver: ["RA"],
    statusApproval: 1,
    approvalDate: "03/02/2022",
  },
  {
    id: 2,
    approvalId: 1081,
    requesterId: 112801,
    namaRequestor: "Adara Fredelia Ulani",
    requestDate: "03/02/2022",
    idMesin: "ZZ08",
    location: "Tangerang Supermall Karawaci",
    jenisAsuransi: "Cash Machine",
    typeTransaksi: "New",
    harga: "Rp15.000.000",
    sla: "tes",
    approver: ["RA", "TS"],
    statusApproval: 2,
    approvalDate: "03/02/2022",
  },
  {
    id: 3,
    approvalId: 1081,
    requesterId: 112801,
    namaRequestor: "Adara Fredelia Ulani",
    requestDate: "03/02/2022",
    idMesin: "ZZ08",
    location: "Tangerang Supermall Karawaci",
    jenisAsuransi: "Cash Machine",
    typeTransaksi: "New",
    harga: "Rp15.000.000",
    sla: "tes",
    approver: ["RA", "TS"],
    statusApproval: 1,
    approvalDate: "03/02/2022",
  },
  {
    id: 4,
    approvalId: 1081,
    requesterId: 112801,
    namaRequestor: "Adara Fredelia Ulani",
    requestDate: "03/02/2022",
    idMesin: "ZZ08",
    location: "Tangerang Supermall Karawaci",
    jenisAsuransi: "Cash Machine",
    typeTransaksi: "New",
    harga: "Rp15.000.000",
    sla: "tes",
    approver: ["TS"],
    statusApproval: 2,
    approvalDate: "03/02/2022",
  },
];

export const dummyApprover = [
  {
    initial: "RA",
    name: "Roy Axter",
    division: "ATM Site Management Head",
  },
  {
    initial: "BA",
    name: "Bambang Karsono Adi",
    division: "Head of Digital Banking, Branchless & Partnership",
  },
  {
    initial: "TS",
    name: "Trisna L. M. Siahaan",
    division: "ATM Business Head",
  },
];

export default dataDummy;
