/* eslint-disable import/prefer-default-export */
const actionPembukaan = [{ name: 'View Detail', url: '/rencana-bisnis/detail-pembukaan', type:'view' }, { name: 'Update', url: '/rencana-bisnis/detail-pembukaan', type:'edit' }, { name: 'Delete', url: '/rencana-bisnis/detail-pembukaan', type:'delete' }];
const actionPenutupan = [{ name: 'View Detail', url: '/rencana-bisnis/detail-pembukaan', type:'view' }, { name: 'Update', url: '/rencana-bisnis/detail-pembukaan', type:'edit' }, { name: 'Delete', url: '/rencana-bisnis/detail-pembukaan', type:'delete' }];

export const dataTablePembukaan = [
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
  { id: '#1025', oldLocation: '-', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', newLoc: 'MTN.CIMBN Syariah', submissionDate: '28/09/2020', tglLapor: '30/09/2020', mesin: 'CRM', cityAsli: '-', action: { actionPembukaan },},
];
export const dataTablePenutupan = [
  { mesin: 'ATM', id: '#1977', location: 'SBY.EBL.Grand City Surabaya -1', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', jaboOrOut: 'Out', tglTarik: '28/09/2020', tglLapor: '30/09/2020', due: '-', action: { actionPenutupan },},
  { mesin: 'ATM', id: '#1977', location: 'SBY.EBL.Grand City Surabaya -1', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', jaboOrOut: 'Out', tglTarik: '28/09/2020', tglLapor: '30/09/2020', due: '-', action: { actionPenutupan },},
  { mesin: 'ATM', id: '#1977', location: 'SBY.EBL.Grand City Surabaya -1', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', jaboOrOut: 'Out', tglTarik: '28/09/2020', tglLapor: '30/09/2020', due: '-', action: { actionPenutupan },},
  { mesin: 'ATM', id: '#1977', location: 'SBY.EBL.Grand City Surabaya -1', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', jaboOrOut: 'Out', tglTarik: '28/09/2020', tglLapor: '30/09/2020', due: '-', action: { actionPenutupan },},
  { mesin: 'ATM', id: '#1977', location: 'SBY.EBL.Grand City Surabaya -1', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', jaboOrOut: 'Out', tglTarik: '28/09/2020', tglLapor: '30/09/2020', due: '-', action: { actionPenutupan },},
  { mesin: 'ATM', id: '#1977', location: 'SBY.EBL.Grand City Surabaya -1', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', jaboOrOut: 'Out', tglTarik: '28/09/2020', tglLapor: '30/09/2020', due: '-', action: { actionPenutupan },},
  { mesin: 'ATM', id: '#1977', location: 'SBY.EBL.Grand City Surabaya -1', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', jaboOrOut: 'Out', tglTarik: '28/09/2020', tglLapor: '30/09/2020', due: '-', action: { actionPenutupan },},
  { mesin: 'ATM', id: '#1977', location: 'SBY.EBL.Grand City Surabaya -1', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', jaboOrOut: 'Out', tglTarik: '28/09/2020', tglLapor: '30/09/2020', due: '-', action: { actionPenutupan },},
  { mesin: 'ATM', id: '#1977', location: 'SBY.EBL.Grand City Surabaya -1', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', jaboOrOut: 'Out', tglTarik: '28/09/2020', tglLapor: '30/09/2020', due: '-', action: { actionPenutupan },},
  { mesin: 'ATM', id: '#1977', location: 'SBY.EBL.Grand City Surabaya -1', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', jaboOrOut: 'Out', tglTarik: '28/09/2020', tglLapor: '30/09/2020', due: '-', action: { actionPenutupan },},
  { mesin: 'ATM', id: '#1977', location: 'SBY.EBL.Grand City Surabaya -1', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', jaboOrOut: 'Out', tglTarik: '28/09/2020', tglLapor: '30/09/2020', due: '-', action: { actionPenutupan },},
  { mesin: 'ATM', id: '#1977', location: 'SBY.EBL.Grand City Surabaya -1', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', jaboOrOut: 'Out', tglTarik: '28/09/2020', tglLapor: '30/09/2020', due: '-', action: { actionPenutupan },},
  { mesin: 'ATM', id: '#1977', location: 'SBY.EBL.Grand City Surabaya -1', city: 'Lombok Tengah', pic: 'Dharma', alasan: 'New Branch', jaboOrOut: 'Out', tglTarik: '28/09/2020', tglLapor: '30/09/2020', due: '-', action: { actionPenutupan },},
];
export const dataTableHistories = [
  { date: '02/02/2020', time: '10:20:32', PIC: 'Hermawan', newLoc: '42', reOpen: '32', newBranch: 23,},
  { date: '02/02/2020', time: '10:20:32', PIC: 'Hermawan', newLoc: '42', reOpen: '32', newBranch: 23,},
  { date: '02/02/2020', time: '10:20:32', PIC: 'Hermawan', newLoc: '42', reOpen: '32', newBranch: 23,},
  { date: '02/02/2020', time: '10:20:32', PIC: 'Hermawan', newLoc: '42', reOpen: '32', newBranch: 23,},
  { date: '02/02/2020', time: '10:20:32', PIC: 'Hermawan', newLoc: '42', reOpen: '32', newBranch: 23,},
  { date: '02/02/2020', time: '10:20:32', PIC: 'Hermawan', newLoc: '42', reOpen: '32', newBranch: 23,},
  { date: '02/02/2020', time: '10:20:32', PIC: 'Hermawan', newLoc: '42', reOpen: '32', newBranch: 23,},
  { date: '02/02/2020', time: '10:20:32', PIC: 'Hermawan', newLoc: '42', reOpen: '32', newBranch: 23,},
  { date: '02/02/2020', time: '10:20:32', PIC: 'Hermawan', newLoc: '42', reOpen: '32', newBranch: 23,},
  { date: '02/02/2020', time: '10:20:32', PIC: 'Hermawan', newLoc: '42', reOpen: '32', newBranch: 23,},
  { date: '02/02/2020', time: '10:20:32', PIC: 'Hermawan', newLoc: '42', reOpen: '32', newBranch: 23,},
];

export const dataTableSummary = [
  { rowLabels: 'Dharma', target: 21, sisaTarget: 10, submission: 11, sudahLapor: 7, sisaLapor: 4,},
  { rowLabels: 'Hermawan', target: 21, sisaTarget: 10, submission: 11, sudahLapor: 7, sisaLapor: 4,},
  { rowLabels: 'Ind Timur', target: 21, sisaTarget: 10, submission: 11, sudahLapor: 7, sisaLapor: 4,},
  { rowLabels: 'Jabo', target: 21, sisaTarget: 10, submission: 11, sudahLapor: 7, sisaLapor: 4,},
  { rowLabels: 'Kalimantan', target: 21, sisaTarget: 10, submission: 11, sudahLapor: 7, sisaLapor: 4,},
  { rowLabels: 'Purwandi', target: 21, sisaTarget: 10, submission: 11, sudahLapor: 7, sisaLapor: 4,},
  { rowLabels: 'Robby Hendri', target: 21, sisaTarget: 10, submission: 11, sudahLapor: 7, sisaLapor: 4,},
  { rowLabels: 'Saut Tobing', target: 21, sisaTarget: 10, submission: 11, sudahLapor: 7, sisaLapor: 4,},
  { rowLabels: 'Setya Widjayanto', target: 21, sisaTarget: 10, submission: 11, sudahLapor: 7, sisaLapor: 4,},
];