/* eslint-disable no-else-return */
const constansts = {};

constansts.color = {
  primaryDark: "#780000",
  primaryHard: "#DC241F",
  primaryMedium: "#FF7774",
  primarySoft: "#FFBAB9",
  primaryUltaSoft: "#FFE9E9",
  secondaryMedium: "#FFB443",
  secondarySoft: "#FFD595",
  secondaryUltraSoft: "#FFECD1",
  grayMedium: "#BCC8E7",
  graySoft: "#E6EAF3",
  grayUltraSoft: "#F4F7FB",
  white: "#FFFFFF",
  dark: "#2B2F3C",
  black: "#000000",
};

constansts.API_MAP_KEY = process.env.REACT_APP_API_MAP_KEY;
constansts.apiHost = `${process.env.REACT_APP_API_DOMAIN}/masterrbbservices/v1`;
constansts.apiDomain = process.env.REACT_APP_API_DOMAIN;
constansts.userServiceBaseUrl = `${constansts.apiDomain}/api/v1/users/api/v1`;
constansts.URL_API_SERVICE = `${process.env.REACT_APP_API_DOMAIN}/masterrbbservices/v1`;
constansts.popupTimeout = `${process.env.REACT_APP_POPUP_TIMEOUT}`;

// Modeling Service
constansts.MODELINGS_SERVICE = `${process.env.REACT_APP_API_DOMAIN}/analysismodelingservice/v1`;

// Implementation Service
constansts.IMPLEMENTATION_SERVICE = `${process.env.REACT_APP_API_DOMAIN}/implementationservice/v1`;

// Monitoring Service
constansts.MONITORING_SERVICE = `${process.env.REACT_APP_API_DOMAIN}/monitoringinformationservice/v1`;

// Environment Premisses
constansts.ENVIRONTMENT_SERVICE = `${process.env.REACT_APP_API_DOMAIN}/environmentpremisesservice/v1`;

// Environment Premisses
constansts.PROJECT_MANAGEMENT_SERVICE = `${process.env.REACT_APP_API_DOMAIN}/projectmanageservice/v1`;

// File Management
constansts.FILE_MANAGEMENT_SERVICE = `${process.env.REACT_APP_API_DOMAIN}/filemanageservice/v1`;
// File Management
constansts.ASSET_MANAGEMENT_SERVICE = `${process.env.REACT_APP_API_DOMAIN}/assetservice/v1`;

// procurement
constansts.getStatusProcurement = (param) => {
  if (param === 1) {
    return "Waiting Negotiation";
  } else if (param === 2) {
    return "Negotiation";
  } else if (param === 3) {
    return "Deal Negotiation";
  } else if (param === 4) {
    return "Renegotiation";
  } else {
    return null;
  }
};

constansts.progressProcurement = (param) => {
  if (param === 1) {
    return "1";
  } else if (param === 2) {
    return "2";
  } else if (param === 3) {
    return "3";
  } else {
    return null;
  }
};

// RBB IMPLEMENTATION
constansts.lastStatus = (param) => {
  if (param === 1) {
    return "1";
  } else if (param === 2) {
    return "2";
  } else if (param === 3) {
    return "3";
  } else if (param === 4) {
    return "4";
  } else if (param === 5) {
    return "5";
  } else if (param === 6) {
    return "6";
  } else if (param === 7) {
    return "7";
  } else if (param === 8) {
    return "8";
  } else if (param === 9) {
    return "9";
  } else if (param === 10) {
    return "10";
  } else if (param === 11) {
    return "11";
  } else if (param === 12) {
    return "12";
  } else {
    return null;
  }
};

constansts.month = (param) => {
  return `${param}`;
};

export default constansts;

export const dataTypeLokasi = [
  { value: "-", name: "- Pilih Tipe Lokasi -" },
  { value: "Airport", name: "Airport" },
  { value: "Business Center", name: "Business Center" },
  { value: "Education", name: "Education" },
  { value: "Gas Station", name: "Gas Station" },
  { value: "Hospital", name: "Hospital" },
  { value: "Hotel", name: "Hotel" },
  { value: "Industry", name: "Industry" },
  { value: "Mall", name: "Mall" },
  { value: "Office Building", name: "Office Building" },
  { value: "Resindential", name: "Resindential" },
  { value: "Restaurant", name: "Restaurant" },
  { value: "Supermarket", name: "Supermarket" },
  { value: "Others", name: "Others" },
];

export const branches = [
  { id: "NAA", value: "Jakarta - Graha CIMB Niaga" },
  { id: "GND", value: "Jakarta - Graha CIMB Niaga" },
  { id: "RTP", value: "Jakarta - Mall Ratu Plaza" },
  { id: "SEB", value: "Jakarta - Stock Exchange Building" },
  { id: "SNC", value: "Jakarta - Sentral Senayan II" },
  { id: "BEJ", value: "Jakarta - BEJ" },
  { id: "SNY", value: "Jakarta - Senayan City" },
  { id: "PCP", value: "Jakarta - Pacific Place" },
  { id: "MTR", value: "Jakarta - Millennium Centennial Center" },
  { id: "MET", value: "Jakarta - Wisma Metropolitan" },
  { id: "MNS", value: "Jakarta - Menara Satrio" },
  { id: "ATJ", value: "Jakarta - Universitas Atmajaya" },
  { id: "CTW", value: "Jakarta - Citywalk" },
  { id: "NGA", value: "Jakarta - Wisma Keiai" },
  { id: "THR", value: "Jakarta - Plaza Sinar Mas Land" },
  { id: "DGI", value: "Jakarta - Grand Indonesia" },
  { id: "PLI", value: "Jakarta - Plaza Indonesia" },
  { id: "BNI", value: "Jakarta - Pejompongan" },
  { id: "TEB", value: "Jakarta - Tebet" },
  { id: "TBM", value: `Jakarta - L'Avenue` },
  { id: "ABS", value: "Jakarta - Mall Ambassador" },
  { id: "CPW", value: "Jakarta - Ciputra World Mall" },
  { id: "GSB", value: "Jakarta - Gatot Subroto" },
  { id: "JDC", value: "Jakarta - Bellagio" },
  { id: "KPL", value: "Jakarta - Kuningan Plaza" },
  { id: "DKK", value: "Jakarta - Kota Kasablanka" },
  { id: "KNN", value: "Jakarta - Tempo Scan" },
  { id: "STU", value: "Jakarta - Setiabudi" },
  { id: "DAM", value: "Jakarta - Daan Mogot" },
  { id: "TMT", value: "Jakarta - Tomang Tol" },
  { id: "HGG", value: "Jakarta - Green Garden" },
  { id: "NPI", value: "JAKARTA - PURI INDAH" },
  { id: "TGH", value: "Jakarta - AKR Tower" },
  { id: "KJR", value: "Jakarta - Kebon Jeruk Intercon" },
  { id: "DLM", value: "Jakarta - Lippo Mall Puri" },
  { id: "SLI", value: "Jakarta - Wisma Slipi" },
  { id: "CTP", value: "Jakarta - Central Park" },
  { id: "TAG", value: "Jakarta - Mall Taman Anggrek" },
  { id: "DCP", value: "Jakarta - Central Park Mall" },
  { id: "CIN", value: "Jakarta - Pondok Indah Icon" },
  { id: "MTO", value: "Jakarta - Metro Pondok Indah" },
  { id: "WSA", value: "Jakarta - Wisma Pondok Indah" },
  { id: "PDX", value: "Jakarta - Pondok Indah Plaza 3" },
  { id: "GDC", value: "Jakarta - Mall Gandaria City" },
  { id: "KBL", value: "Jakarta - Sultan Iskandar Muda" },
  { id: "ACD", value: "Jakarta - Arcadia Simatupang" },
  { id: "PM2", value: "Jakarta - PIM 2" },
  { id: "OSQ", value: "Jakarta - South Quarter" },
  { id: "CNR", value: "Jakarta - Cinere" },
  { id: "DEP", value: "Depok - Margonda" },
  { id: "DUI", value: "Depok - FISIP UI" },
  { id: "FLT", value: "Jakarta - Sentraya" },
  { id: "PMH", value: "Jakarta - Permata Hijau" },
  { id: "PGD", value: "Jakarta - Pondok Gede" },
  { id: "FTA", value: "Jakarta - Fatmawati 20" },
  { id: "KJT", value: "Jakarta - Pasar Induk Kramat Jati" },
  { id: "MLW", value: "Jakarta - Melawai" },
  { id: "WBC", value: "Jakarta - Warung Buncit" },
  { id: "KMG", value: "Jakarta - Kemang Raya 1" },
  { id: "DRK", value: "Jakarta - Kemang Raya 47 (DL @ Home)" },
  { id: "KPM", value: "Jakarta - Pasar Minggu" },
  { id: "PPM", value: "Jakarta - Panglima Polim" },
  { id: "BOG", value: "Bogor - Padjajaran" },
  { id: "TAJ", value: "Bogor - V Point" },
  { id: "DBS", value: "Bogor - Botani Square" },
  { id: "CBN", value: "Cibinong - Mayor Oking" },
  { id: "BJG", value: "Bogor - Cisalak" },
  { id: "CLS", value: "Bogor - Cileungsi" },
  { id: "BGR", value: "Bogor - Juanda" },
  { id: "STL", value: "Bogor - Plaza Niaga Sentul" },
  { id: "KWC", value: "Bogor - Cibubur Kota Wisata" },
  { id: "CBB", value: "Jakarta - Cibubur Indah" },
  { id: "CBR", value: "Jakarta - Cibubur Citra Grand" },
  { id: "DAS", value: "Bogor - AEON Mall Sentul" },
  { id: "CAS", value: "Tangerang - Alam Sutera Icon" },
  { id: "GDS", value: "Tangerang - Gading Serpong" },
  { id: "CLN", value: "Cilegon - City Square" },
  { id: "TGR", value: "Tangerang - Tangerang City" },
  { id: "TKK", value: "Tangerang - Kondominium Golf Karawaci" },
  { id: "LGC", value: "Tangerang - LG Cirarab" },
  { id: "RPA", value: "Tangerang - Pinangsia" },
  { id: "DLP", value: "Tangerang - Supermall Karawaci" },
  { id: "TNE", value: "Tangerang - Daan Mogot" },
  { id: "TCB", value: "Tangerang - Taman Cibodas" },
  { id: "TKS", value: "Tangerang - Kisamaun" },
  { id: "BTO", value: "Tangerang - Bintaro Griya Niaga" },
  { id: "CLD", value: "Tangerang - Ciledug" },
  { id: "BTR", value: "Jakarta - Bintaro Sektor I" },
  { id: "ICB", value: "Tangerang - ITC BSD" },
  { id: "PMB", value: "Tangerang - Pasar Modern BSD" },
  { id: "DAE", value: "Tangerang - AEON Mall" },
  { id: "PMG", value: "Tangerang - Pamulang Permai" },
  { id: "GOP", value: "Tangerang - Green Office Park" },
  { id: "LCB", value: "Bekasi - Lippo Cikarang" },
  { id: "MMC", value: "Bekasi - BEFA Square" },
  { id: "JBB", value: "Bekasi - Jababeka" },
  { id: "KRW", value: "Karawang - Tuparev" },
  { id: "LGI", value: "Bekasi - LG Cibitung" },
  { id: "HKK", value: "Bekasi - Cikarang Hankook" },
  { id: "SMU", value: "Bekasi - Samsung" },
  { id: "KMP", value: "Bekasi - Kemang Pratama" },
  { id: "SMB", value: "Bekasi - Summarecon" },
  { id: "JBK", value: "Bekasi - Juanda" },
  { id: "BKB", value: "Bekasi - Bekasi Barat" },
  { id: "KGP", value: "Jakarta - Kelapa Gading TN" },
  { id: "GCK", value: "Jakarta - Jakarta Garden City" },
  { id: "GPL", value: "Jakarta - Mall Kelapa Gading" },
  { id: "KLP", value: "Jakarta - Kelapa Gading LB" },
  { id: "BGI", value: "Jakarta - Bukit Gading Indah" },
  { id: "MAG", value: "Jakarta - Mal Artha Gading" },
  { id: "SUN", value: "Jakarta - Sunter" },
  { id: "CPK", value: "Jakarta - Cempaka Putih 68" },
  { id: "TJP", value: "Jakarta - Tanjung Priok" },
  { id: "KMN", value: "Jakarta - Kalimalang" },
  { id: "MTM", value: "Jakarta - Matraman" },
  { id: "JGR", value: "Jakarta - Jatinegara" },
  { id: "RWN", value: "Jakarta - Rawamangun Pratama" },
  { id: "KPG", value: "Jakarta - Pulo Gadung" },
  { id: "RWM", value: "Jakarta - Rawamangun Arion" },
  { id: "PIC", value: "Jakarta - Pasar Induk Cipinang" },
  { id: "PLU", value: "Jakarta - Pluit" },
  { id: "JDU", value: "Jakarta - Jembatan Dua" },
  { id: "MKR", value: "Jakarta - Muara Karang" },
  { id: "PNA", value: "Jakarta - Pantai Indah Kapuk" },
  { id: "TPM", value: "Jakarta - Taman Palem" },
  { id: "KCG", value: "Jakarta - Citra Garden 1" },
  { id: "DPA", value: "Jakarta - PIK Avenue" },
  { id: "TLG", value: "Jakarta - Teluk Gong" },
  { id: "JLB", value: "Jakarta - Taman Duta Mas" },
  { id: "EMP", value: "Jakarta - Mal Emporium Pluit" },
  { id: "SBR", value: "Jakarta - Sawah Besar" },
  { id: "GMK", value: "Jakarta - Lindeteves Trade Center" },
  { id: "JYK", value: "Jakarta - Jayakarta" },
  { id: "KOT", value: "Jakarta - Kota" },
  { id: "KAC", value: "Jakarta - Ancol" },
  { id: "LKS", value: "Jakarta - Mangga Besar" },
  { id: "MGD", value: "Jakarta - Mangga Dua Rutex" },
  { id: "HYW", value: "Jakarta - Hayam Wuruk" },
  { id: "PAR", value: "Jakarta - Pintu Air" },
  { id: "KAR", value: "Jakarta - Karang Anyar" },
  { id: "PKC", value: "Jakarta - Pintu Kecil" },
  { id: "GMA", value: "Jakarta - Gajah Mada" },
  { id: "PCN", value: "Jakarta - Sangaji" },
  { id: "SPO", value: "Jakarta - Suryopranoto" },
  { id: "JLI", value: "Jakarta - Jembatan Lima" },
  { id: "CKI", value: "Jakarta - Cikini" },
  { id: "GMI", value: "Jakarta - Gambir" },
  { id: "KBS", value: "Jakarta - Kebon Sirih" },
  { id: "MTG", value: "Jakarta - Menteng" },
  { id: "WHT", value: "Jakarta - Wahid Hasyim" },
  { id: "TMR", value: "Jakarta - Tomang Raya" },
  { id: "CID", value: "Jakarta - Cideng" },
  { id: "ROM", value: "Jakarta - Roxy Mas" },
  { id: "BTL", value: "Jakarta - Metro Tanah Abang" },
  { id: "TAK", value: "Jakarta - Tanah Abang Blok A" },
  { id: "BAA", value: "Bandung - Asia Afrika" },
  { id: "BSK", value: "Bandung - Setiabudi" },
  { id: "BLE", value: "Bandung - Lembang" },
  { id: "ATN", value: "Bandung - Astana Anyar" },
  { id: "BTC", value: "Bandung - Pajajaran" },
  { id: "BSM", value: "Sumedang - Abdurachman" },
  { id: "CRB", value: "Cirebon - Yos Sudarso" },
  { id: "CBL", value: "Cirebon - Balong Indah Plaza" },
  { id: "CRN", value: "Cirebon - Siliwangi" },
  { id: "DGO", value: "Bandung - Dago" },
  { id: "KBP", value: "Bandung - Kota Baru Parahyangan" },
  { id: "BOT", value: "Bandung - Otista" },
  { id: "BBD", value: "Cimahi - Borma Dakota" },
  { id: "BCD", value: "Cimahi - Raya Tagog" },
  { id: "RIU", value: "Bandung - Riau" },
  { id: "DTB", value: "Bandung - ITB" },
  { id: "CNJ", value: "Cianjur - Cokroaminoto" },
  { id: "PWA", value: "Purwakarta - Veteran" },
  { id: "SKM", value: "Sukabumi - Martadinata" },
  { id: "LMO", value: "Bandung - Lembong" },
  { id: "SAR", value: "Bandung - Sumber Sari" },
  { id: "KPB", value: "Bandung - Kopo Bihbul" },
  { id: "BGA", value: "Garut - Ahmad Yani" },
  { id: "BAT", value: "Bandung - Buah Batu" },
  { id: "BAY", value: "Bandung - Ahmad Yani" },
  { id: "BLS", value: "Bandung - Lingkar Selatan" },
  { id: "TSK", value: "Tasikmalaya - Yudanegara" },
  { id: "TSM", value: "Tasikmalaya - HZ Mustofa" },
  { id: "SMG", value: "Semarang - Pemuda 102" },
  { id: "GSS", value: "Semarang - Gatot Subroto" },
  { id: "SIK", value: "Semarang - Kaligawe" },
  { id: "SMT", value: "Semarang - Mataram" },
  { id: "SSL", value: "Semarang - Siliwangi" },
  { id: "SLG", value: "Salatiga - Sudirman" },
  { id: "AYN", value: "Semarang - Gajah Mada" },
  { id: "CNI", value: "Semarang - Candi" },
  { id: "SUG", value: "Semarang - Ungaran" },
  { id: "CDW", value: "Semarang - Cendrawasih" },
  { id: "DTM", value: "Semarang - Tentrem Mall" },
  { id: "TGL", value: "Tegal - Sudirman" },
  { id: "SLW", value: "Tegal - Slawi" },
  { id: "PKL", value: "Pekalongan - Hayam Wuruk" },
  { id: "RYD", value: "Solo - Slamet Riyadi 8" },
  { id: "MNH", value: "Solo - Manahan" },
  { id: "PSL", value: "Solo - Paragon Mall" },
  { id: "SLR", value: "Solo - Slamet Riyadi 136" },
  { id: "KAE", value: "Klaten - Pemuda" },
  { id: "KTS", value: "Solo - Kartasura" },
  { id: "ATM", value: "Solo - ATMI" },
  { id: "KLW", value: "Solo - Mesen Square" },
  { id: "PLR", value: "Solo - Palur" },
  { id: "SBA", value: "Solo - Solo Baru" },
  { id: "KDS", value: "Kudus - Agil Kusumadya" },
  { id: "DBO", value: "Demak - Bintoro" },
  { id: "JPR", value: "Jepara - Diponegoro" },
  { id: "KDU", value: "Kudus - Ahmad Yani" },
  { id: "PTI", value: "Pati - Sudirman" },
  { id: "YOG", value: "Yogyakarta - Sudirman 50" },
  { id: "GJY", value: "Yogyakarta - Gejayan" },
  { id: "PRS", value: "Yogyakarta - Parang Tritis" },
  { id: "DAJ", value: "Yogyakarta - Atmajaya" },
  { id: "YGN", value: "Yogyakarta - Godean" },
  { id: "YSD", value: "Yogyakarta - Sanata Darma" },
  { id: "YSM", value: "Yogyakarta - Sudirman 13" },
  { id: "RSP", value: "Yogyakarta - RS Panti Rapih" },
  { id: "UAM", value: "Yogyakarta - UAJ Mrican" },
  { id: "USP", value: "Yogyakarta - Universitas Sanata Pahingan" },
  { id: "DGM", value: "Yogyakarta - UGM" },
  { id: "DMO", value: "Yogyakarta - Malioboro Mall Yogyakarta" },
  { id: "MGG", value: "Magelang - Rejotumoto" },
  { id: "WNB", value: "Wonosobo - Ahmad Yani" },
  { id: "KBM", value: "Kebumen - Pahlawan" },
  { id: "PRR", value: "Purworejo - Achmad Dahlan" },
  { id: "PRO", value: "Purwokerto - Sudirman" },
  { id: "PUL", value: "Purbalingga - Sudirman" },
  { id: "CLC", value: "Cilacap - Sudirman" },
  { id: "DRO", value: "Surabaya - Darmo" },
  { id: "RDM", value: "Surabaya - Diponegoro" },
  { id: "PKW", value: "Surabaya - Pakuwon" },
  { id: "DTP", value: "Surabaya - Tunjungan Plaza 6" },
  { id: "ADY", value: "Surabaya - Andayani" },
  { id: "JMR", value: "Surabaya - Jemursari" },
  { id: "PTA", value: "Surabaya - Universitas Kristen Petra" },
  { id: "RNK", value: "Surabaya - Rungkut" },
  { id: "HSD", value: "Surabaya - Dharmahusada" },
  { id: "MLO", value: "Surabaya - Mulyosari" },
  { id: "MSS", value: "Surabaya - Pakuwon City" },
  { id: "SKK", value: "Surabaya - Kapas Krampung" },
  { id: "MAR", value: "Surabaya - Manyar Kertoardjo" },
  { id: "KMA", value: "Surabaya - Kembang Jepun" },
  { id: "PAK", value: "Surabaya - Perak" },
  { id: "PSA", value: "Surabaya - Pasar Atom" },
  { id: "DEC", value: "Surabaya - Pakuwon City Mall" },
  { id: "SSD", value: "Surabaya - Sudirman" },
  { id: "TNU", value: "Surabaya - Tunjungan" },
  { id: "PCA", value: "Surabaya - Pucang Anom" },
  { id: "SKA", value: "Surabaya - Klampis" },
  { id: "RMI", value: "Surabaya - Manyar Mega Indah" },
  { id: "TDR", value: "Surabaya - Tidar" },
  { id: "BJN", value: "Bojonegoro - Gajah Mada" },
  { id: "GRS", value: "Gresik - Kartini" },
  { id: "SSM", value: "Surabaya - Bukit Darmo" },
  { id: "SSK", value: "Surabaya - Sungkono" },
  { id: "SDA", value: "Sidoarjo - Ahmad Yani" },
  { id: "JBG", value: "Jombang - Ahmad Yani" },
  { id: "MJK", value: "Mojokerto - Mojopahit" },
  { id: "LMG", value: "Lamongan - Lamongrejo" },
  { id: "JBR", value: "Jember - Diponegoro" },
  { id: "BDW", value: "Bondowoso - Sudirman" },
  { id: "BWI", value: "Banyuwangi - Sudirman" },
  { id: "STB", value: "Situbondo - Sepudi" },
  { id: "MLN", value: "Malang - Basuki Rachmad" },
  { id: "GLN", value: "Malang - Galunggung" },
  { id: "ITN", value: "Malang - ITN" },
  { id: "LMJ", value: "Lumajang - Sudirman" },
  { id: "PSR", value: "Pasuruan - Pasar Besar" },
  { id: "MLM", value: "Malang - Merdeka" },
  { id: "KJM", value: "Malang - Kepanjen" },
  { id: "MDU", value: "Madiun - Pahlawan" },
  { id: "NGW", value: "Ngawi - Sultan Agung" },
  { id: "PRG", value: "Ponorogo - Gajah Mada" },
  { id: "BLR", value: "Blitar - Merdeka" },
  { id: "KED", value: "Kediri - Diponegoro" },
  { id: "TLA", value: "Tulungagung - Sudirman" },
  { id: "DPS", value: "Bali - Thamrin" },
  { id: "DDS", value: "Bali - Dewi Sartika" },
  { id: "KGD", value: "Bali - Kuta Graha" },
  { id: "NDA", value: "Bali - Nusa Dua" },
  { id: "SND", value: "Bali - Sanur" },
  { id: "MLT", value: "Bali - Melati" },
  { id: "SRB", value: "Bali - Singaraja" },
  { id: "UBU", value: "Bali - Ubud" },
  { id: "DMG", value: "Denpasar - Mall Galeria" },
  { id: "KLM", value: "Kupang - Lalamentik" },
  { id: "MTN", value: "Mataram - Pejanggik" },
  { id: "BKT", value: "Medan - Bukit Barisan" },
  { id: "MMY", value: "Medan - M Yamin" },
  { id: "GJH", value: "Medan - Gajah Mada" },
  { id: "KIM", value: "Medan - Marelan" },
  { id: "MSU", value: "Medan - Sutomo Ujung" },
  { id: "MYS", value: "Medan - Yos Sudarso" },
  { id: "DNP", value: "Medan - Centre Point" },
  { id: "MCA", value: "Medan - Cemara Asri" },
  { id: "DPO", value: "Medan - Podomoro City Deli Park" },
  { id: "MDN", value: "Medan - Pemuda" },
  { id: "MKA", value: "Medan - AR Hakim" },
  { id: "MBD", value: "Medan - Bandung" },
  { id: "MDA", value: "Medan - Asia" },
  { id: "MTH", value: "Medan - KS Tubun" },
  { id: "PSI", value: "Pematang Siantar - Merdeka" },
  { id: "TTI", value: "Tebing Tinggi - Sudirman" },
  { id: "CNM", value: "Medan - Icon" },
  { id: "MPO", value: "Medan - Polonia" },
  { id: "JAD", value: "Medan - Juanda" },
  { id: "MGS", value: "Medan - Gatot Subroto" },
  { id: "MBI", value: "Binjai - Sudirman" },
  { id: "RTU", value: "Rantau Prapat - Ahmad Yani" },
  { id: "SIP", value: "Batam - Sei Panas" },
  { id: "BTD", value: "Batam - Batamindo" },
  { id: "BTM", value: "Batam - Nagoya" },
  { id: "ABB", value: "Batam - Adhya Building" },
  { id: "SPN", value: "Batam - Botania" },
  { id: "TOP", value: "Batam - Penuin Centre" },
  { id: "TPN", value: "Tanjung Pinang - Merdeka" },
  { id: "NKR", value: "Pekanbaru - Sudirman" },
  { id: "NGK", value: "Pekanbaru - Tuanku Tambusai" },
  { id: "PKA", value: "Pekanbaru - Riau" },
  { id: "PKP", value: "Pekanbaru - Panam" },
  { id: "DUM", value: "Dumai - Sultan Syarif Qasim" },
  { id: "DRI", value: "Dumai - Duri" },
  { id: "PDG", value: "Padang - Sudirman" },
  { id: "PDK", value: "Padang - Pondok" },
  { id: "PDY", value: "Padang - M Yamin" },
  { id: "JMB", value: "Jambi Sutomo" },
  { id: "LMU", value: "Lampung - Malahayati" },
  { id: "LPG", value: "Lampung - Tanjung Karang" },
  { id: "PPN", value: "Pangkal Pinang - Masjid Jamik" },
  { id: "SDR", value: "Palembang - Sudirman" },
  { id: "PLB", value: "Palembang - Kolonel Atmo" },
  { id: "PMJ", value: "Palembang - Mesjid Lama" },
  { id: "DPI", value: "Palembang - Icon Mall" },
  { id: "BPN", value: "Balikpapan - Ahmad Yani" },
  { id: "MLF", value: "Balikpapan - Ruko Baru" },
  { id: "BLK", value: "Balikpapan - MT Haryono" },
  { id: "SAM", value: "Samarinda - KH Khalid" },
  { id: "SMA", value: "Samarinda - Simpang Merak" },
  { id: "SMR", value: "Samarinda - Bung Tomo" },
  { id: "TRK", value: "Tarakan - Karang Anyar" },
  { id: "BJS", value: "Banjarmasin - Pangeran Samudera" },
  { id: "BJA", value: "Banjarmasin - Banjarbaru" },
  { id: "BNA", value: "Banjarmasin - Ahmad Yani 56" },
  { id: "PKY", value: "Palangkaraya - Murjani" },
  { id: "PON", value: "Pontianak - Tanjungpura" },
  { id: "SAP", value: "Pontianak - Sultan Abdurrahman" },
  { id: "KTG", value: "Ketapang - MT Haryono" },
  { id: "AYI", value: "Makassar - Ahmad Yani" },
  { id: "UHS", value: "Makassar - Bandang" },
  { id: "TRM", value: "Makassar - Trans Studio" },
  { id: "PBU", value: "Makassar - Panakukang" },
  { id: "KND", value: "Kendari - Mandonga" },
  { id: "RTN", value: "Manado - Walanda Maramis" },
  { id: "MND", value: "Manado - Mega Mas" },
  { id: "MAN", value: "Manado - Sam Ratulangi" },
  { id: "AMB", value: "Ambon - Sam Ratulangi" },
  { id: "JYP", value: "Jayapura - Pasifik Permai" },
  { id: "KAA", value: "Mimika - Kuala Kencana" },
  { id: "YSS", value: "Mimika - Budi Utomo" },
  { id: "RDE", value: "Mimika - Ridge Camp" },
  { id: "RP2", value: "Mimika - Tembagapura II" },
  { id: "TP1", value: "Mimika - Tembagapura I" },
  { id: "SMD", value: "Jakarta - Menara Sudirman" },
  { id: "KPI", value: "Jakarta - Kemenag Jakarta Timur" },
  { id: "SBG", value: "Bogor - Juanda (Co-location)" },
  { id: "SVC", value: "Jakarta - Sentraya (Co-location)" },
  { id: "SSP", value: "Tangerang - Serpong  (Co-location)" },
  { id: "SGS", value: "Bandung - Lembong (Co-location)" },
  { id: "KEG", value: "Bandung - Kemenag Kota" },
  { id: "KEB", value: "Bandung - Kemenag Kabupaten" },
  { id: "SCR", value: "Cirebon - Siliwangi (Co-locate)" },
  { id: "SSMR", value: "Semarang - Pemuda 21B" },
  { id: "SSO", value: "Solo - Slamet Riyadi 136 (Co-location)" },
  { id: "SYG", value: "Yogyakarta - Sudirman (Co-location)" },
  { id: "SBY", value: "Surabaya - Darmo (Co-location)" },
  { id: "SDP", value: "Bali - Thamrin (Co-location)" },
  { id: "SML", value: "Malang - Soekarno Hatta" },
  { id: "KUM", value: "Mataram - Kuta Mandalika" },
  { id: "MKS", value: "Makassar - Achmad Yani" },
  { id: "SBM", value: "Banjarmasin - Ahmad Yani (Co-location)" },
  { id: "SSSA", value: "Samarinda - Juanda" },
  { id: "SJM", value: "Jambi - Hayam Wuruk (Co-location)" },
  { id: "SLPG", value: "Lampung - Hasanudin" },
  { id: "SLS", value: "Lhokseumawe - Suka Ramai" },
  { id: "SBNA", value: "Banda Aceh - Peunayong" },
  { id: "SPL", value: "Palembang - Letkol Iskandar" },
  { id: "SPSD", value: "Pekanbaru - Sudirman" },
  { id: "SSPD", value: "Padang - Sudirman (Co-location)" },
  { id: "SSPM", value: "Medan - Gatot Subroto (Co-location)" },
  { id: "SYB", value: "Batam - Mahkota Raya" },
  { id: "KSB", value: "Surabaya - Kemenag Kota" },
  { id: "KMJ", value: "Kas Mobil - Jakarta Tebet 1" },
  { id: "KGS", value: "Kas Mobil - Jakarta Tebet 2" },
  { id: "KMC", value: "Kas Mobil - Jakarta Niaga Tower" },
  { id: "KME", value: "Kas Mobil - Jakarta Kelapa Gading TN" },
  { id: "KMQ", value: "Kas Mobil - Bekasi Cikarang" },
  { id: "KEA", value: "Kas Mobil - Bogor Pajajaran" },
  { id: "KRS", value: "Kas Mobil - Solo" },
  { id: "KNO", value: "Kas Mobil - Jakarta Sawah Besar 2" },
  { id: "KSO", value: "Kas Mobil - Bintaro Griya Niaga" },
  { id: "KMT", value: "Kas Mobil - Alam Sutera Icon" },
  { id: "KMW", value: "Kas Mobil - Jakarta Tomang Tol" },
  { id: "KMB", value: "Kas Mobil - Bandung" },
  { id: "KCN", value: "Kas Mobil - Bandung 2" },
  { id: "KMO", value: "Kas Mobil - Cirebon" },
  { id: "KMR", value: "Kas Mobil - Semarang 1" },
  { id: "KSA", value: "Kas Mobil - Semarang 2" },
  { id: "KDY", value: "Kas Mobil - Yogyakarta 1" },
  { id: "KJS", value: "Kas Mobil - Yogyakarta 2" },
  { id: "KDB", value: "Kas Mobil - Denpasar" },
  { id: "KMH", value: "Kas Mobil - Mataram " },
  { id: "KMU", value: "Kas Mobil - Surabaya 1" },
  { id: "KOR", value: "Kas Mobil - Surabaya 2" },
  { id: "KOL", value: "Kas Mobil -Malang 1" },
  { id: "KMK", value: "Kas Mobil - Malang 2" },
  { id: "KOM", value: "Kas Mobil - Makassar" },
  { id: "KOS", value: "Kas Mobil - Samarinda" },
  { id: "KMM", value: "Kas Mobil - Medan" },
  { id: "KMF", value: "Kas Mobil - Palembang" },
  { id: "KOB", value: "Kas Mobil - Batam" },
  { id: "KPE", value: "Kas Mobil - Pekanbaru" },
  { id: "KPT", value: "Kas Mobil - Pontianak" },
  { id: "KLY", value: "Kas Mobil - Lampung" },
  { id: "KSP", value: "Kas Mobil - Padang" },
];

export const jensKomList = [
  { value: "- Pilih Jenis Komunikasi -", name: "- Pilih Jenis Komunikasi -" },
  { value: "VSAT", name: "VSAT" },
  { value: "Fixed Line", name: "Fixed Line" },
  { value: "Wireless", name: "Wireless" },
];

export const dataRuangAtm = [
  { value: "-", name: "- Pilih Ruang Atm -" },
  { value: "Bersama", name: "Bersama" },
  { value: "Sendiri", name: "Sendiri" },
  { value: "Lobby Gedung", name: "Lobby Gedung" },
  { value: "Build by CIMB", name: "Build by CIMB" },
  { value: "Other", name: "Other" },
];

export const dataCard = [
  {
    title: "Kebutuhan",
    type: "need",
    url: "/vendor-management/orders/kebutuhan",
    urlVendor: "/vendor-orders/kebutuhan",
  },
  {
    title: "Mesin",
    type: "mesin",
    url: "/vendor-management/orders/mesin",
    urlVendor: "/vendor-orders/mesin",
  },
  {
    title: "Booth",
    type: "booth",
    url: "/vendor-management/orders/booth",
    urlVendor: "/vendor-orders/booth",
  },
  {
    title: "Signage",
    type: "signage",
    url: "/vendor-management/orders/signage",
    urlVendor: "/vendor-orders/signage",
  },
  {
    title: "Aktivasi",
    type: "activation",
    url: "/implementation/vendor",
    urlVendor: "/implementation/vendor",
  },
  {
    title: "Terminasi",
    type: "termination",
    url: "/vendor-management/orders/terminasi",
    urlVendor: "/vendor-orders/terminasi",
  },
  {
    title: "Jarkom",
    type: "jarkom",
    url: "/vendor-management/orders/jarkom",
    urlVendor: "/vendor-orders/jarkom",
  },
  {
    title: "Parameter",
    type: "parameter",
    url: "/implementation/vendor",
    urlVendor: "/implementation/vendor",
  },
  {
    title: "Keamanan",
    type: "security",
    url: "/vendor-management/orders/keamanan",
    urlVendor: "/vendor-orders/keamanan",
  },
  {
    title: "Clearliness Quality",
    type: "clearlinessQuality",
    url: "/environment-premises/clearliness-quality",
    urlVendor: "/vendor-digitalisasi/clearliness-quality",
  },
  {
    title: "Premises Quality",
    type: "premisesQuality",
    url: "/environment-premises/premisses-quality/vendor-surveysite",
    urlVendor: "/vendor-digitalisasi/premisses-quality/vendor-surveysite",
  },
];
export const routeRef = [
  {
    type: "Vendor SLM",
    url: "/vendor-management/digitalisasi/slm",
    urlVendor: "/vendor-digitalisasi/slm",
  },
  {
    type: "SLM",
    url: "/vendor-management/digitalisasi/slm",
    urlVendor: "/vendor-digitalisasi/slm",
  },
  {
    type: "Vendor FLM",
    url: "/vendor-management/digitalisasi/vendorflm",
    urlVendor: "/vendor-digitalisasi/vendorflm",
  },
  {
    type: "FLM",
    url: "/vendor-management/digitalisasi/vendorflm",
    urlVendor: "/vendor-digitalisasi/vendorflm",
  },
  {
    type: "Vendor CCTV",
    url: "/vendor-management/digitalisasi/vendorcctv",
    urlVendor: "/vendor-digitalisasi/vendorcctv",
  },
  {
    type: "Vendor FLM RPL",
    url: "/vendor-management/digitalisasi/vendor-flm-rpl",
    urlVendor: "/vendor-digitalisasi/vendor-flm-rpl",
  },
  {
    type: "Inventory Cassette",
    url: "/vendor-management/digitalisasi/inventory-cassette",
    urlVendor: "/vendor-digitalisasi/inventory-cassette",
  },
  {
    type: "Site Quality",
    url: "/vendor-management/digitalisasi/site-quality",
    urlVendor: "/vendor-digitalisasi/site-quality",
  },
  {
    type: "Vendor Maintenance Premises",
    url: "/environment-premises/premisses-quality/vendor-maintenance",
    urlVendor: "/vendor-digitalisasi/premisses-quality/vendor-maintenance",
  },
  {
    type: "Media Promosi",
    url: "/media-promosi/media-promosi-quality/vendor-media-promosi",
    urlVendor: "/vendor-digitalisasi/vendor-media-promosi",
  },
  {
    type: "Vendor Kebersihan",
    url: "/environment-premises/clearliness-quality",
    urlVendor: "/vendor-digitalisasi/clearliness-quality",
  },
];

export const listBankLain = [
  { title: "BANK BRI", code: "002" },
  { title: "BANK BCA", code: "014" },
  { title: "BANK MANDIRI", code: "008" },
  { title: "BANK BNI", code: "009" },
  { title: "BANK BNI SYARIAH", code: "427" },
  { title: "BANK SYARIAH MANDIRI (BSM)", code: "451" },
  { title: "BANK CIMB NIAGA", code: "022" },
  { title: "BANK CIMB NIAGA SYARIAH", code: "022" },
  { title: "BANK MUAMALAT", code: "147" },
  { title: "BANK BTPN", code: "213" },
  { title: "BANK BTPN SYARIAH", code: "547" },
  { title: "BANK PERMATA", code: "013" },
  { title: "BANK PERMATA SYARIAH", code: "013" },
  { title: "BANK DBS INDONESIA", code: "046" },
  { title: "DIGIBANK", code: "046" },
  { title: "BANK BRI SYARIAH", code: "422" },
  { title: "BANK BTN", code: "200" },
  { title: "BANK DANAMON", code: "011" },
  { title: "BANK MAYBANK (BII)", code: "016" },
  { title: "BANK MEGA", code: "426" },
  { title: "BANK SINARMAS", code: "153" },
  { title: "BANK COMMONWEALTH", code: "950" },
  { title: "BANK OCBC NISP", code: "028" },
  { title: "BANK BUKOPIN", code: "441" },
  { title: "BANK BUKOPIN SYARIAH", code: "521" },
  { title: "BANK BCA SYARIAH", code: "536" },
  { title: "BANK LIPPO", code: "026" },
  { title: "CITIBANK", code: "031" },
];
