// eslint-disable-next-line import/prefer-default-export
export const defaultDataBast = {
  noReference: '-',
  letterDate: '-',
  nameLandlord: '-',
  locationArea: '-',
  locationAddress: '-',
  locationName: '-',
  locationCity: '-',
  atmId: '-',
  latitude: '-',
  longitude: '-',
  areaName: '-',
  cityName: '-',
  phoneFLM: null,
  phoneSLM: null,
  phoneCIT: null,
  phoneCR: null,
  ticketNumber: '-',
  locationId: '-',
  idMesin: '-',
  jobType: '-',
  requestDate: '-',
  processingDate: '-',
  notesDescription: '-',
  engineerTelephoneNumber: null,
  linkVideo: null,
  partNumber: null,
  installationDate: null,
  picInstall: null,
  requesterName: null,
  brandTypeName: null,
  stickerId: null,
  version: null,
  photoFrontCimb: null,
  datefrontCimb: null,
  photoLeftCimb: null,
  dateLeftCimb: null,
  photoRightCimb: null,
  dateRightCimb: null,
  photoRearCimb: null,
  dateRearCimb: null,
  photoFrontVendor: null,
  dateFrontVendor: null,
  photoLeftVendor: null,
  dateLeftVendor: null,
  photoRightVendor: null,
  dateRightVendor: null,
  photoRearVendor: null,
  dateRearVendor: null,
  photoFLMVendor: null,
  photoSLMVendor: null,
  photoList: [],
  vendorDetails: [
    {
      check: "checkedCR",
      phone: "",
      name: "",
      key: "CR",
    },
    {
      check: "checkedFLM",
      phone: "",
      name: "",
      key: "FLM",
    },
    {
      check: "checkedSLM",
      phone: "",
      value: "",
      key: "SLM",
    },
    {
      check: "checkedJarkom",
      phone: "",
      name: "",
      key: "Jaringan",
    },
    {
      check: "checkedSecurity",
      phone: "",
      name: "",
      key: "Maintenance",
    },
    {
      check: "checkedPromosi",
      phone: "",
      name: "",
      key: "Promosi",
    },
    {
      check: "checkedSurvey",
      phone: "",
      name: "",
      key: "Survey",
    },
    {
      check: "checkedOther",
      phone: "",
      name: "",
      key: "Other",
    },],
  picVendor: ""
};