export const dummyDataMesinATM = [
  {
    id: 1,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    machineType: "Mesin Baru",
    pullDate: "12-12-2022",
    idMesin: "AD0023",
    snMesin: "SN0001",
    location: "JKT.SPBU CIPAYUNG",
    snUps: "SNUPS0001",
    jumlahKaset: 10,
    jumlahReject: 10,
    cardBin: 2,
    kunciTombak: 2,
    kunciFasciaAtas: 2,
    kunciFasciaBawah: 2,
    platAntiSkimmer: 2,
    pinCover: 1,
    ups: 2,
    dvr: 2,
    cctv: 2,
    booth: 2,
    fm: 2,
    pmDate: "12-12-2021",
    pmStatus: "ok",
    kondisiCat: "ok",
    kodisiKunci: "ok",
    kondisiSticker: "ok",
    stickerId: 12342,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2020",
    bastStaging: "BAST DIGITAL",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "Gudang",
  },
  {
    id: 2,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    machineType: "Mesin Baru",
    pullDate: "12-12-2022",
    idMesin: "AD0023",
    snMesin: "SN0001",
    location: "JKT.SPBU CIPAYUNG",
    snUps: "SNUPS0001",
    jumlahKaset: 10,
    jumlahReject: 10,
    cardBin: 2,
    kunciTombak: 2,
    kunciFasciaAtas: 2,
    kunciFasciaBawah: 2,
    platAntiSkimmer: 2,
    pinCover: 1,
    ups: 2,
    dvr: 2,
    cctv: 2,
    booth: 2,
    fm: 2,
    pmDate: "12-12-2021",
    pmStatus: "ok",
    kondisiCat: "ok",
    kodisiKunci: "ok",
    kondisiSticker: "ok",
    stickerId: 12342,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2020",
    bastStaging: "BAST DIGITAL",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "Gudang",
  },
  {
    id: 3,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    machineType: "Mesin Baru",
    pullDate: "12-12-2022",
    idMesin: "AD0023",
    snMesin: "SN0001",
    location: "JKT.SPBU CIPAYUNG",
    snUps: "SNUPS0001",
    jumlahKaset: 10,
    jumlahReject: 10,
    cardBin: 2,
    kunciTombak: 2,
    kunciFasciaAtas: 2,
    kunciFasciaBawah: 2,
    platAntiSkimmer: 2,
    pinCover: 1,
    ups: 2,
    dvr: 2,
    cctv: 2,
    booth: 2,
    fm: 2,
    pmDate: "12-12-2021",
    pmStatus: "ok",
    kondisiCat: "ok",
    kodisiKunci: "ok",
    kondisiSticker: "ok",
    stickerId: 12342,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2020",
    bastStaging: "BAST DIGITAL",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "Gudang",
  },
  {
    id: 4,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    machineType: "Mesin Baru",
    pullDate: "12-12-2022",
    idMesin: "AD0023",
    snMesin: "SN0001",
    location: "JKT.SPBU CIPAYUNG",
    snUps: "SNUPS0001",
    jumlahKaset: 10,
    jumlahReject: 10,
    cardBin: 2,
    kunciTombak: 2,
    kunciFasciaAtas: 2,
    kunciFasciaBawah: 2,
    platAntiSkimmer: 2,
    pinCover: 1,
    ups: 2,
    dvr: 2,
    cctv: 2,
    booth: 2,
    fm: 2,
    pmDate: "12-12-2021",
    pmStatus: "ok",
    kondisiCat: "ok",
    kodisiKunci: "ok",
    kondisiSticker: "ok",
    stickerId: 12342,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2020",
    bastStaging: "BAST DIGITAL",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "Gudang",
  },
  {
    id: 5,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    machineType: "Mesin Baru",
    pullDate: "12-12-2022",
    idMesin: "AD0023",
    snMesin: "SN0001",
    location: "JKT.SPBU CIPAYUNG",
    snUps: "SNUPS0001",
    jumlahKaset: 10,
    jumlahReject: 10,
    cardBin: 2,
    kunciTombak: 2,
    kunciFasciaAtas: 2,
    kunciFasciaBawah: 2,
    platAntiSkimmer: 2,
    pinCover: 1,
    ups: 2,
    dvr: 2,
    cctv: 2,
    booth: 2,
    fm: 2,
    pmDate: "12-12-2021",
    pmStatus: "ok",
    kondisiCat: "ok",
    kodisiKunci: "ok",
    kondisiSticker: "ok",
    stickerId: 12342,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2020",
    bastStaging: "BAST DIGITAL",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "Gudang",
  },
  {
    id: 6,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    machineType: "Mesin Baru",
    pullDate: "12-12-2022",
    idMesin: "AD0023",
    snMesin: "SN0001",
    location: "JKT.SPBU CIPAYUNG",
    snUps: "SNUPS0001",
    jumlahKaset: 10,
    jumlahReject: 10,
    cardBin: 2,
    kunciTombak: 2,
    kunciFasciaAtas: 2,
    kunciFasciaBawah: 2,
    platAntiSkimmer: 2,
    pinCover: 1,
    ups: 2,
    dvr: 2,
    cctv: 2,
    booth: 2,
    fm: 2,
    pmDate: "12-12-2021",
    pmStatus: "ok",
    kondisiCat: "ok",
    kodisiKunci: "ok",
    kondisiSticker: "ok",
    stickerId: 12342,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2020",
    bastStaging: "BAST DIGITAL",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "Gudang",
  },
  {
    id: 7,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    machineType: "Mesin Baru",
    pullDate: "12-12-2022",
    idMesin: "AD0023",
    snMesin: "SN0001",
    location: "JKT.SPBU CIPAYUNG",
    snUps: "SNUPS0001",
    jumlahKaset: 10,
    jumlahReject: 10,
    cardBin: 2,
    kunciTombak: 2,
    kunciFasciaAtas: 2,
    kunciFasciaBawah: 2,
    platAntiSkimmer: 2,
    pinCover: 1,
    ups: 2,
    dvr: 2,
    cctv: 2,
    booth: 2,
    fm: 2,
    pmDate: "12-12-2021",
    pmStatus: "ok",
    kondisiCat: "ok",
    kodisiKunci: "ok",
    kondisiSticker: "ok",
    stickerId: 12342,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2020",
    bastStaging: "BAST DIGITAL",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "Gudang",
  },
  {
    id: 8,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    machineType: "Mesin Baru",
    pullDate: "12-12-2022",
    idMesin: "AD0023",
    snMesin: "SN0001",
    location: "JKT.SPBU CIPAYUNG",
    snUps: "SNUPS0001",
    jumlahKaset: 10,
    jumlahReject: 10,
    cardBin: 2,
    kunciTombak: 2,
    kunciFasciaAtas: 2,
    kunciFasciaBawah: 2,
    platAntiSkimmer: 2,
    pinCover: 1,
    ups: 2,
    dvr: 2,
    cctv: 2,
    booth: 2,
    fm: 2,
    pmDate: "12-12-2021",
    pmStatus: "ok",
    kondisiCat: "ok",
    kodisiKunci: "ok",
    kondisiSticker: "ok",
    stickerId: 12342,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2020",
    bastStaging: "BAST DIGITAL",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "Gudang",
  },
  {
    id: 9,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    machineType: "Mesin Baru",
    pullDate: "12-12-2022",
    idMesin: "AD0023",
    snMesin: "SN0001",
    location: "JKT.SPBU CIPAYUNG",
    snUps: "SNUPS0001",
    jumlahKaset: 10,
    jumlahReject: 10,
    cardBin: 2,
    kunciTombak: 2,
    kunciFasciaAtas: 2,
    kunciFasciaBawah: 2,
    platAntiSkimmer: 2,
    pinCover: 1,
    ups: 2,
    dvr: 2,
    cctv: 2,
    booth: 2,
    fm: 2,
    pmDate: "12-12-2021",
    pmStatus: "ok",
    kondisiCat: "ok",
    kodisiKunci: "ok",
    kondisiSticker: "ok",
    stickerId: 12342,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2020",
    bastStaging: "BAST DIGITAL",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "Gudang",
  },
  {
    id: 10,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    machineType: "Mesin Baru",
    pullDate: "12-12-2022",
    idMesin: "AD0023",
    snMesin: "SN0001",
    location: "JKT.SPBU CIPAYUNG",
    snUps: "SNUPS0001",
    jumlahKaset: 10,
    jumlahReject: 10,
    cardBin: 2,
    kunciTombak: 2,
    kunciFasciaAtas: 2,
    kunciFasciaBawah: 2,
    platAntiSkimmer: 2,
    pinCover: 1,
    ups: 2,
    dvr: 2,
    cctv: 2,
    booth: 2,
    fm: 2,
    pmDate: "12-12-2021",
    pmStatus: "ok",
    kondisiCat: "ok",
    kodisiKunci: "ok",
    kondisiSticker: "ok",
    stickerId: 12342,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2020",
    bastStaging: "BAST DIGITAL",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "Gudang",
  },
];

export const dummyDataUPS = [
  {
    id: 1,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    upsType: "UPS Baru",
    pullDate: "12-12-2022",
    location: "JKT.SPBU CIPAYUNG",
    snUps: "SNUPS0001",
    ups: 2,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2022",
    bastStaging: "BAST Digital",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "Gudang",
  },
  {
    id: 2,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    upsType: "UPS Baru",
    pullDate: "12-12-2022",
    location: "JKT.SPBU CIPAYUNG",
    snUps: "SNUPS0001",
    ups: 2,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2022",
    bastStaging: "BAST Digital",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "Jl Nelayan Brt 317, Dki Jakarta",
  },
  {
    id: 3,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    upsType: "UPS Baru",
    pullDate: "12-12-2022",
    location: "JKT.SPBU CIPAYUNG",
    snUps: "SNUPS0001",
    ups: 2,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2022",
    bastStaging: "BAST Digital",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "Jl Sumur Batu IV Bl B/10, Dki Jakarta",
  },
  {
    id: 4,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    upsType: "UPS Baru",
    pullDate: "12-12-2022",
    location: "JKT.SPBU CIPAYUNG",
    snUps: "SNUPS0001",
    ups: 2,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2022",
    bastStaging: "BAST Digital",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "Jl Jend A Yani III/15, Sumatera Utara",
  },
  {
    id: 5,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    upsType: "UPS Baru",
    pullDate: "12-12-2022",
    location: "JKT.SPBU CIPAYUNG",
    snUps: "SNUPS0001",
    ups: 2,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2022",
    bastStaging: "BAST Digital",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "Jl Arteri Mangga Dua Raya Mal Mangga Dua Bl B/89, Dki Jakarta",
  },
  {
    id: 6,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    upsType: "UPS Baru",
    pullDate: "12-12-2022",
    location: "JKT.SPBU CIPAYUNG",
    snUps: "SNUPS0001",
    ups: 2,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2022",
    bastStaging: "BAST Digital",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "AA. Maramis 116K, Jawa Timur",
  },
  {
    id: 7,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    upsType: "UPS Baru",
    pullDate: "12-12-2022",
    location: "JKT.SPBU CIPAYUNG",
    snUps: "SNUPS0001",
    ups: 2,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2022",
    bastStaging: "BAST Digital",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "Jl Sisingamangaraja 191, Sumatera Utara",
  },
  {
    id: 8,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    upsType: "UPS Baru",
    pullDate: "12-12-2022",
    location: "JKT.SPBU CIPAYUNG",
    snUps: "SNUPS0001",
    ups: 2,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2022",
    bastStaging: "BAST Digital",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "Jl Ciputat Raya 30 ABC, Dki Jakarta",
  },
  {
    id: 9,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    upsType: "UPS Baru",
    pullDate: "12-12-2022",
    location: "JKT.SPBU CIPAYUNG",
    snUps: "SNUPS0001",
    ups: 2,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2022",
    bastStaging: "BAST Digital",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "Mal Ambasador Ruko Ground Floor/12, JL Prof Dr Satrio, Setiabudi",
  },
  {
    id: 10,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    upsType: "UPS Baru",
    pullDate: "12-12-2022",
    location: "JKT.SPBU CIPAYUNG",
    snUps: "SNUPS0001",
    ups: 2,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2022",
    bastStaging: "BAST Digital",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "Jl H Dilun Raya 113 Kel Ulujami Kec Pesanggrahan, Dki Jakarta",
  },
];

export const dummyDataDVR = [
  {
    id: 1,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    dvrType: "DVR Baru",
    pullDate: "-",
    location: "JKT.SPBU CIPAYUNG",
    snDvr: "SNDVR0001",
    dvr: 2,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2022",
    bastStaging: "BAST Digital",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "Gudang",
  },
  {
    id: 2,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    dvrType: "DVR Baru",
    pullDate: "12-12-2022",
    location: "JKT.SPBU CIPAYUNG",
    snDvr: "SNDVR0001",
    dvr: 2,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2022",
    bastStaging: "BAST Digital",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "Jl Nelayan Brt 317, Dki Jakarta",
  },
  {
    id: 3,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    dvrType: "DVR Baru",
    pullDate: "12-12-2022",
    location: "JKT.SPBU CIPAYUNG",
    snDvr: "SNDVR0001",
    dvr: 2,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2022",
    bastStaging: "BAST Digital",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "Jl Sumur Batu IV Bl B/10, Dki Jakarta",
  },
  {
    id: 4,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    dvrType: "DVR Baru",
    pullDate: "12-12-2022",
    location: "JKT.SPBU CIPAYUNG",
    snDvr: "SNDVR0001",
    dvr: 2,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2022",
    bastStaging: "BAST Digital",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "Jl Jend A Yani III/15, Sumatera Utara",
  },
  {
    id: 5,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    dvrType: "DVR Baru",
    pullDate: "12-12-2022",
    location: "JKT.SPBU CIPAYUNG",
    snDvr: "SNDVR0001",
    dvr: 2,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2022",
    bastStaging: "BAST Digital",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "Jl Arteri Mangga Dua Raya Mal Mangga Dua Bl B/89, Dki Jakarta",
  },
  {
    id: 6,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    dvrType: "DVR Baru",
    pullDate: "12-12-2022",
    location: "JKT.SPBU CIPAYUNG",
    snDvr: "SNDVR0001",
    dvr: 2,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2022",
    bastStaging: "BAST Digital",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "AA. Maramis 116K, Jawa Timur",
  },
  {
    id: 7,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    dvrType: "DVR Baru",
    pullDate: "12-12-2022",
    location: "JKT.SPBU CIPAYUNG",
    snDvr: "SNDVR0001",
    dvr: 2,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2022",
    bastStaging: "BAST Digital",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "Jl Sisingamangaraja 191, Sumatera Utara",
  },
  {
    id: 8,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    dvrType: "DVR Baru",
    pullDate: "12-12-2022",
    location: "JKT.SPBU CIPAYUNG",
    snDvr: "SNDVR0001",
    dvr: 2,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2022",
    bastStaging: "BAST Digital",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "Jl Ciputat Raya 30 ABC, Dki Jakarta",
  },
  {
    id: 9,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    dvrType: "DVR Baru",
    pullDate: "12-12-2022",
    location: "JKT.SPBU CIPAYUNG",
    snDvr: "SNDVR0001",
    dvr: 2,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2022",
    bastStaging: "BAST Digital",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "Mal Ambasador Ruko Ground Floor/12, JL Prof Dr Satrio, Setiabudi",
  },
  {
    id: 10,
    activityNumber: "A-11341",
    warehouseNumber: "223412",
    dvrType: "DVR Baru",
    pullDate: "12-12-2022",
    location: "JKT.SPBU CIPAYUNG",
    snDvr: "SNDVR0001",
    dvr: 2,
    userReq: "Riado",
    userControl: "Ramlan",
    tglStaging: "12-12-2022",
    bastStaging: "BAST Digital",
    reservedFor: "Deden Hidayat",
    statusLokasiMesin: "Jl H Dilun Raya 113 Kel Ulujami Kec Pesanggrahan, Dki Jakarta",
  },
];

export const dataSummary = [
  {
    name: "Total Mesin",
    totalMesin: 13.946,
    ready: 12.809,
    notReady: 1.137,
  },
  {
    name: "Total UPS",
    totalMesin: 1.946,
    ready: 1.403,
    notReady: 543,
  },
  {
    name: "Total DVR",
    totalMesin: 3.231,
    ready: 1.232,
    notReady: 1.999,
  },
];
